CREATE TABLE CASINO(
	ID VARCHAR2(50) PRIMARY KEY,
	PW VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(50) UNIQUE NOT NULL,
	MONEY NUMBER DEFAULT 0
);

INSERT INTO CASINO(ID, PW, NICKNAME, MONEY) VALUES('피카츄', '1234', '피카츄', 50);
INSERT INTO CASINO(ID, PW, NICKNAME, MONEY) VALUES('파이리', '1234', '파이리', 50);
INSERT INTO CASINO(ID, PW, NICKNAME, MONEY) VALUES('꼬부기', '1234', '꼬부기', 50);
----
--SELECT * FROM CASINO;

SELECT * FROM CASINO;

DELETE FROM CASINO;